apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/nfs-vol/"
    server: "172.16.10.105"